const BIOSIM_CONFIG = {
  spawners: {
    herbivore: { x: 120, y: 120 },
    carnivore: { x: 220, y: 160 },
    plant: { x: 180, y: 220 },
  },

  world: {
    // Global world / layout
    initialHerbivores: 0,
    initialCarnivores: 0,
    plantMargin: 9,
    innerSpawnAreaRatio: 0.5,
    animalMovementPadding: 28,
    spawnerDragRadius: 18,
    spawnerOpenCloseSpeed: 9,
    edgeThicketWidth: 56,
    edgeThicketPushStrength: 210,

    // Plant spawning
    plantSpawnerMinSeconds: 0.2,
    plantSpawnerMaxSeconds: 1.2,
    plantSpawnerRadius: 34,
    plantSpawnerClusterChance: 0.32,
    plantSpawnerClusterMin: 2,
    plantSpawnerClusterMax: 5,

    // Plants
    networkRadius: 72,
    supportNeighborsPerPlant: 5,
    bridgeSearchRadius: 160,
    feedingRange: 48,
    bridgeStep: 27,
    localSproutDistance: 12,
    baseBodyFeedRate: 6,
    baseUpkeep: 0.32,
    neighborUpkeepDiscount: 0.01,
    minimumUpkeepRatio: 0.45,
    intakeMultiplierMin: 0.65,
    intakeMultiplierMax: 1.5,
    initialNutrientsMin: 20,
    initialNutrientsMax: 60,
    maxNutrientsMin: 120,
    maxNutrientsMax: 150,
    proliferateThresholdMin: 50,
    proliferateThresholdMax: 60,
    proliferateAttemptsPerSecond: 0.32,
    frontierProliferationThresholdBonus: 30,
    frontierProliferationAttemptsPerSecond: 1.35,
    proliferateAttemptCost: 0.5,
    plantProliferationCooldownSeconds: 6.5,
    wiltFadeRate: 0.42,
    wiltRecoveryNutrients: 5,
    plantGrowInSeconds: 0.32,
    sacrificeThreshold: 10,
    sacrificeWiltThreshold: 0.2,
    sacrificeNeighborHealthThreshold: 0.1,
    sacrificeRecoveredShare: 0.95,
    starvationDeathSeconds: 4.5,
    plantInteractionRadius: 10,
    plantPhysicalRadius: 7,

    // Roots / nutrient network
    rootUpkeepPerPixel: 0.0001,
    exploratoryRootUpkeepFull: 0.03,
    packetSpeedPixelsPerSecond: 50,
    packetDispatchPerSecond: 0.9,
    minPacketAmount: 1,
    maxPacketAmount: 2,
    supportRootMinGrowthSeconds: 0.9,
    supportRootMaxGrowthSeconds: 2.9,
    supportRootRetractSeconds: 1.3,
    supportRootWeakRetractSeconds: 0.4,
    exploratoryRootMinGrowthSeconds: 1.2,
    exploratoryRootMaxGrowthSeconds: 3.2,
    exploratoryRootRetractSeconds: 1.25,
    exploratoryRootSearchMinNutrients: 24,
    exploratoryRootMaxPerPlant: 1,
    exploratoryBodyDistanceMin: 72,
    exploratoryBodyDistanceMax: 280,

    // Bodies / corpses
    bodyNaturalDecay: 2,
    bodyRemovalThreshold: 0.19,
    herbivoreCorpseNutrients: 300,
    herbivoreEatenCorpseFraction: 0.5,
    carnivoreCorpseNutrients: 600,

    // Herbivores
    herbivoreSpawnMinSeconds: 1,
    herbivoreSpawnMaxSeconds: 2,
    herbivoreSpeedMin: 70,
    herbivoreSpeedMax: 80,
    herbivoreHungerRateMinRatio: 0.01,
    herbivoreHungerRateMaxRatio: 0.02,
    herbivoreGrazeRate: 11,
    herbivoreGrazeHungerReliefRatioPerNutrient: 0.02,
    herbivoreFinishPlantNutrients: 4.5,
    herbivoreThreatRange: 60,
    herbivoreSenseRange: 600,
    herbivorePhysicalRadius: 4.5,
    herbivoreBaseHangRadius: 42,

    //Herb Mating
    herbivoreMateNourishmentRatio: 0.6,
    herbivoreMateSearchRange: 120,
    herbivoreMateContactDistance: 10,
    herbivoreMateChancePerSecond: 0.3,
    herbivoreMateHungerCostRatio: 0.12,
    herbivoreMateCooldownSeconds: 12,
    herbivoreBabyScale: 0.55,
    herbivoreBabyGrowthNutrients: 18,

    // Carnivores
    carnivoreSpawnMinSeconds: 3,
    carnivoreSpawnMaxSeconds: 6,
    carnivoreSpeedMin: 130,
    carnivoreSpeedMax: 150,
    carnivoreHungerRateMinRatio: 0.02,
    carnivoreHungerRateMaxRatio: 0.04,
    carnivoreKillHungerReliefRatio: 0.6,
    carnivoreSenseRange: 400,
    carnivorePhysicalRadius: 5.5,
    carnivorePlantBrushStrength: 0.55,
    carnivorePlantSelfPushStrength: 0.36,
    carnivorePlantVelocityDamping: 0.5,
    carnivorePostKillPauseSeconds: 0.38,
    carnivoreBaseHangRadius: 54,
    
    //Carni Mating
    carnivoreMateNourishmentRatio: 0.7,
    carnivoreMateSearchRange: 160,
    carnivoreMateContactDistance: 12,
    carnivoreMateChancePerSecond: 0.2,
    carnivoreMateHungerCostRatio: 0.16,
    carnivoreMateCooldownSeconds: 18,
    carnivoreBabyScale: 0.6,
    carnivoreBabyGrowthNutrients: 45,

    //Carni Fighting    
    carnivoreFightPopulationThreshold: 4,
    carnivoreFightChancePerSecond: 0.03,
    carnivoreFightSearchRange: 130,
    carnivoreFightContactDistance: 12,
    carnivoreFightDurationSeconds: 1.15,
    carnivoreFightCooldownSeconds: 10,

    // Shared animal movement / needs
    animalHungerMax: 100,
    animalContactRadius: 7,
    animalTurnRate: 15,
    animalAcceleration: 100,
    animalDeceleration: 100,
    animalMotionDrag: 3.4,
    animalTopSpeedFactor: 1.18,
    animalChaseStarvationGraceSeconds: 10,
    animalSpawnInitialHungerMinRatio: 0.33,
    animalSpawnInitialHungerMaxRatio: 0.47,
    idleStandChance: 0.44,
    idleReturnHomeChance: 0.22,
    idlePauseMinSeconds: 0.8,
    idlePauseMaxSeconds: 2.8,
    idleWalkMinSeconds: 0.9,
    idleWalkMaxSeconds: 2.6,
    idleArrivalDistance: 8,
  },
};
